---
name: Mkdocs build PDFs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

jobs:
  build_pdfs:
    runs-on: ubuntu-latest
    name: Build PDFs
    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        run: ${PWD}/build_pdf/build_all.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdf/*
